

//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MvcApplication5
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class tobyEntities : DbContext
{
    public tobyEntities()
        : base("name=tobyEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<account> account { get; set; }

    public DbSet<Goods> Goods { get; set; }

    public DbSet<CUSTOMER> CUSTOMER { get; set; }

}

}

