
//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MvcApplication5.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CUSTOMER
{

    public int CST_NUM { get; set; }

    public string CST_ID { get; set; }

    public string CST_PWD { get; set; }

    public string CST_NAME { get; set; }

    public string CST_PHONE_A { get; set; }

    public string CST_PHONE_B { get; set; }

    public string CST_ADR { get; set; }

    public string CST_GRADE { get; set; }

    public string CST_EMAIL { get; set; }

    public int CST_USED { get; set; }

    public System.DateTime CST_REG_DATE { get; set; }

    public System.DateTime CST_MOD_DATE { get; set; }

    public string CST_MILEAGE_CD { get; set; }

}

}
